apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secret
data:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:0KDxQeOM7/pO24h08zfQKzy8PY4Jp3ZEaHeumpD5odw=,iv:KNBGu9RvdlhtNWepx0YbyxKmRcfrKrP8u8s1GZ3GsYQ=,tag:cMaIJoZ+G2zrB6Je0522tw==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:T6HSYwSBW0GCewpF+o4Frm4V6jY6i5P1rrU/JetPXsA=,iv:d3s2Ga2aW4ekVbN3s+El/Fo9hQti87Heh99QkZoP7s0=,tag:uKBZFYHOfe4yvcAj72zYyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s09z34n5t8v08wgwkfa2fd2w8lcaadd5gkpdw0dqyku2ln73msgsg6lfsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTStvRjhLUkJlQjRwZ2FN
            VmFoR0dDdStCQ2ZXeUNabTk2UERwaWRPY0Z3CnpxYkxlQWFLUVlzUnYrakFwMFc3
            TjYrd28ycUpFK2FwTFRLVFk3RFNVaVkKLS0tIFBkdFJkOTlZanhwR24wb3JsTWpH
            dmQ3V1RMNGovK1dMcmtCakYxY3g3dm8KLSjfQ77FejV5aW1NjIaurXUQPvBXtzIv
            0GKtD4T/NUjHMOEp3lqFgnnT7bYv9VoJYJvw5Stqem8blu2q591BKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T11:24:57Z"
    mac: ENC[AES256_GCM,data:m4gDh2ussk4BgkB/z1mPiuqHjJ8/m4rFFHxtiC6LNHUZlv154QO43G25jbuaq9FoTqzJrM6gGX9FVZHIBzJf/tpK4Ik84Hn5k6BzCXR4vQK/bYcxSLAJ15HC1h88MznyZEJCWP/HY5dHP6OhK7MjJHqVlhQWWEw4TKET64Rcot0=,iv:YUz40peCXQWG3GTi9IqHEnEMOX+U2mFvyjLNgiDBisE=,tag:xBN8ad5E3UsMxjX/mXO+fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
