apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
    namespace: kube-system
stringData:
    PROWLARR__API_KEY: ENC[AES256_GCM,data:Latbh9F13kxtH/RNWNPOhU5kwhU4+Q==,iv:s5eU3JASIaOM2pj2WcTc5hMyE/eUBc25OgHc/5Zvv1E=,tag:bhAM7uqh7nivwuJcJ06h/w==,type:str]
    PROWLARR__POSTGRES_HOST: ENC[AES256_GCM,data:n+ZTL2iYM73jkHVZfXGRREa0XJ+bbB8qXJxnPMqtRP3xE8kel9Ksbw==,iv:535YHBaZdqCZw+5Z8rxljYe54nxsAXvuMF4gVzsb+lU=,tag:ds0r4i7ixu79UoXfl89DvA==,type:str]
    PROWLARR__POSTGRES_PORT: ENC[AES256_GCM,data:tFZcIg==,iv:R9BVZiNh+PjE6Ej1EhyzyCdQYkmDg+OkXGN1RqVZyA8=,tag:o0xJeHHnxcP2krwloHsXxQ==,type:str]
    PROWLARR__POSTGRES_USER: ENC[AES256_GCM,data:hYbY05FO5o8=,iv:QXwaDnXJue32n1Ll8Fjzov5IbgUY8SYW0a+PFeNMO9Q=,tag:lESn1Kv8DQjRlQxGGS3t7A==,type:str]
    PROWLARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:iwqlD5cvJGIMnVHOQNmuDUQ=,iv:0K86EbYPmXdIccIBu4MZEd1cdjdz23WIDM+Wlkm5k+8=,tag:Rs8wRoDvgdjer4D3daEd8A==,type:str]
    PROWLARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:dIHJcrRFuHOMKL152Q==,iv:+4YieQ/otQPs/Y6N7Gfoy3vxQH8p8hGkzK1SS3OkWvU=,tag:qIc9nXqIoOxsvlXauKag6A==,type:str]
    PROWLARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:7fB+j1imX9bHjTyT,iv:pX8U4MvjxZaNOlgWlKXs9kPIdKZtP2kENT1juqz78x0=,tag:5MwzcLblj46zWtx03oNYhQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:yJEbJQ0MEyMTmUXp9jlU8Yfctv54L+Dipak=,iv:N8oGPSuiP6MG1B1gUlZg3hegHdcn3vBQpqkD3LNFuJ0=,tag:2EIgLAmEcYar6pJfM2wmUA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:SOpKc1Qx+zNzlWOCWChr4tRZM4TL1n10XEW0X3ixuHsj538oWu5O/A==,iv:ZG9hfok/wOnBtw0xwoWjQsIsm0jY6zfo3IFF3ZY27Ms=,tag:WOyBiNDeMt/RLGtF6mC+8A==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:IYl3iC6eteA=,iv:lBySu2aqpVN9dLMWwYHjomLos9S6wMVSrcrtkqU0oM8=,tag:uE+VzV+kDaNlR+PLbFsMSQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:wF/Ger1bgF8jJFMnlTtwdZI=,iv:liX3UwMx+6mG4ldsjFjRgtQubCmhocJe726Zw8m3f2o=,tag:bqaXKCiol8Ptmp3tUe7Mxg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:P33jk0El1Vw3yB08zHgp12X18MPjWm4=,iv:orIEwIMGns1APFTwcKqsedeh2zA50tqqwwUXHrpWsnY=,tag:93J9AjNuueSLQ1zBd58Slw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s09z34n5t8v08wgwkfa2fd2w8lcaadd5gkpdw0dqyku2ln73msgsg6lfsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTStvRjhLUkJlQjRwZ2FN
            VmFoR0dDdStCQ2ZXeUNabTk2UERwaWRPY0Z3CnpxYkxlQWFLUVlzUnYrakFwMFc3
            TjYrd28ycUpFK2FwTFRLVFk3RFNVaVkKLS0tIFBkdFJkOTlZanhwR24wb3JsTWpH
            dmQ3V1RMNGovK1dMcmtCakYxY3g3dm8KLSjfQ77FejV5aW1NjIaurXUQPvBXtzIv
            0GKtD4T/NUjHMOEp3lqFgnnT7bYv9VoJYJvw5Stqem8blu2q591BKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-13T11:59:05Z"
    mac: ENC[AES256_GCM,data:BRcPpWN7jsDYvKUoqjLxc8w6IETynQ9dPRkLMDnvMB5Jypx7MvPd/41ZTKaTbj+e48Ek79kZasTUIXggT6xuZ4f6PSrIVB4GlK7U2SYdddYavk06aPbGK8X2Mbf46Q15pbkyLzGyV2iLME8Y8fS1Q517lj2EiJ59wJ3qrZEZbCo=,iv:mjQHlJJEOrr+Kb3al4tutTnAZ9Wl9JLY4Xjyoip8jNI=,tag:jnqFKs1Tvn/3Grm0g0XzMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
