apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: observability
stringData:
    ALERTMANAGER_UPTIMEROBOT_HEARTBEAT_URL: ENC[AES256_GCM,data:/KoFattMoOLcaqc=,iv:jKg9QKFNu2sS2J45UHstqGThCcJorq5KgCFnSAAoVG8=,tag:KWR7fdMsGhxzBKVBBk/mhw==,type:str]
    ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:2MvCZQ==,iv:Pja4c+o+/a9xcra0IOe67rZ5o6EPG74Hw7YqB8Ygj7w=,tag:dwXHc5QIG681jGhSYQZBrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s09z34n5t8v08wgwkfa2fd2w8lcaadd5gkpdw0dqyku2ln73msgsg6lfsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTStvRjhLUkJlQjRwZ2FN
            VmFoR0dDdStCQ2ZXeUNabTk2UERwaWRPY0Z3CnpxYkxlQWFLUVlzUnYrakFwMFc3
            TjYrd28ycUpFK2FwTFRLVFk3RFNVaVkKLS0tIFBkdFJkOTlZanhwR24wb3JsTWpH
            dmQ3V1RMNGovK1dMcmtCakYxY3g3dm8KLSjfQ77FejV5aW1NjIaurXUQPvBXtzIv
            0GKtD4T/NUjHMOEp3lqFgnnT7bYv9VoJYJvw5Stqem8blu2q591BKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-15T04:36:35Z"
    mac: ENC[AES256_GCM,data:z9SKjNjyzKo5yoT6iGYKsCrln4N4BtgMHYJRD5C9n9rQmjXKgijsDZp+GekEI5Fh+B28+xrFryZ350I3rXpork1tRjJdpnUcGnI1kGxxXWzi1ejtUBNKRBtFJVOL/w+nL3R4i6E4mhmYx7mprruHnMOvdyU4p6lSOGzYM0yUkkM=,iv:Xp+RALpYsz3NBS5oINjUFRUYrI1Am2Wb8xO7L3OJjNk=,tag:UvMFJU3Q/dlYja/MtxNobw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
