apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:9YPnLa1mIruPvFZRabqpryK/oCoNbVWL2DO6yfuTgjycTCVk,iv:xBK9IyIiSMWw2rkcC0Epl6MXxef4DMw/CT/jB7qdJB8=,tag:y02xywP5MxeG+hJMCqr2FA==,type:str]
    credentials.json: ENC[AES256_GCM,data:m6LZ8zvtZn4ZXYcMBS4qn355RBgvDDkMe6Rr313seUEZX1H/ASWZeUuQkNo3GGafbdiGReFUdaN8oCmMK8K7JM413qp6/ZDNc5J5D0nfn8/8Mo+L0kfBzWJrpXZSkDOKljXKPZVnsJAV0gwm5hOIg+Mbovc1egHedXthAwVlpIgP2im1dFFspeXnPxUmqnHAXZol/eEOK67QyIHjIhiKrC5ziW9iOABEuQHf06KgDg==,iv:ViowtrPLJ33V7U4m/2GJc0zBiJxAOqFwlmY5+uiyGh0=,tag:lJqm6rSa4nnSH4xkv4KMwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s09z34n5t8v08wgwkfa2fd2w8lcaadd5gkpdw0dqyku2ln73msgsg6lfsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc1VkdmRhVG9LaEFTaWZu
            M21IRmptamt5WWg1NjQ0eWRyMDhiVHFFcTE4CnNGOUFxeFRIbTEyeStVeXVFL05a
            dm8rWVY0NVlsalM4Q2d3alZEN201ZWcKLS0tIFE5RS9CUHRXR0d5a21sb3VqTGhK
            aTNuQ0NrdnQ1TU9OT1c1K29ScGdRQTAKtyV/rn6AGQyzAZxWMl/E61Nujk01RfUp
            lIxeGX8qhxF9bDyQZGIg4B8/qIENg3JBffXh2TQdsHIDz9GAijE+rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T01:29:08Z"
    mac: ENC[AES256_GCM,data:6su/F6R5vjfKMiUKod9Vd9tBbYVlcl3ddx2Zxt8NzDW6pFoVLtOgUGxvblhwxd1HHXqTd0R4IEZ+/jxpgmPTBooFHK1v5rmkxM01L0izwR2ua1/JLGhpQBtgVAfaBxI29yNwiI4z/h78hbTireWy5btAWhR1vi4o/2WVXbaWR3A=,iv:MWrxXX2i9bEEXXR3s4oOXqEkLdsv1j9eOrpTe69c7L8=,tag:AD6GCfIs44W5vBJcfWcKOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
