---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: thanos
      version: 15.7.29
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: redis
      namespace: database
  valuesFrom:
    - targetPath: objstoreConfig.config.access_key
      kind: Secret
      name: thanos-bucket-secret
      valuesKey: access_key
    - targetPath: objstoreConfig.config.secret_key
      kind: Secret
      name: thanos-bucket-secret
      valuesKey: secret_key
  values:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.37.1
    objstoreConfig:
      type: s3
      config:
        bucket: sol-thanos
        endpoint: s3.us-east-005.backblazeb2.com
    receive:
      enabled: false
      networkPolicy:
        enabled: false
    queryFrontend:
      enabled: true
      replicaCount: 1
      config: &config |-
        type: REDIS
        config:
          addr: >-
            redis-node-0.redis-headless.database.svc.cluster.local:26379,
            redis-node-1.redis-headless.database.svc.cluster.local:26379,
            redis-node-2.redis-headless.database.svc.cluster.local:26379
          db: 13
          master_name: redis-master
          password: ${SECRET_REDIS_PASSWORD}
      ingress:
        enabled: true
        ingressClassName: internal
        hostname: &host thanos-query-frontend.${SECRET_DOMAIN}
        tls: true
        extraTls:
          - hosts:
              - *host
      networkPolicy:
        enabled: false
    query:
      enabled: true
      replicaCount: 1
      replicaLabel: ["__replica__"]
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: observability
      stores: ["thanos.${SECRET_DOMAIN}:10901"]
      networkPolicy:
        enabled: false
    bucketweb:
      enabled: true
      replicaCount: 1
      networkPolicy:
        enabled: false
    compactor:
      enabled: true
      extraFlags:
        - --compact.concurrency=4
        - --delete-delay=30m
      retentionResolutionRaw: 3d
      retentionResolution5m: 10d
      retentionResolution1h: 20d
      persistence:
        enabled: true
        storageClass: freenas-iscsi-csi
        size: 10Gi
      networkPolicy:
        enabled: false
    storegateway:
      enabled: true
      replicaCount: 1
      config: *config
      persistence:
        enabled: true
        storageClass: freenas-iscsi-csi
        size: 10Gi
      networkPolicy:
        enabled: false
    ruler:
      enabled: true
      replicaCount: 1
      replicaLabel: __replica__
      alertmanagers: ["http://alertmanager-operated.observability.svc.cluster.local:9093"]
      extraFlags: ["--web.prefix-header=X-Forwarded-Prefix"]
      config: |-
        groups:
          - name: PrometheusWatcher
            rules:
              - alert: PrometheusDown
                annotations:
                  summary: A Prometheus has disappeared from Prometheus target discovery
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
                for: 5m
                labels:
                  severity: critical
      persistence:
        enabled: true
        storageClass: freenas-iscsi-csi
        size: 10Gi
      networkPolicy:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
