apiVersion: v1
kind: Secret
metadata:
    name: thanos-bucket-secret
    namespace: observability
stringData:
    access_key: ENC[AES256_GCM,data:DAe6Rj305ECvbSHdGbV06qqccACEp+xQobRsAJEp,iv:YiyVJWN6EFfm+KzgU/vnDTnaraGRmRLo2P2KFsNO844=,tag:oj0XFopD8JO+XR71tB42RQ==,type:str]
    secret_key: ENC[AES256_GCM,data:qWmWTgWHIPeiyzis8f5oCv92HZ7XfVwIZAcoAR7D,iv:IcLPYhVGo8DQRUFZiKLJHEVrKe6T3SOwXLSXeYaxJVc=,tag:BuME9yveyiK9FYN2shpiRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s09z34n5t8v08wgwkfa2fd2w8lcaadd5gkpdw0dqyku2ln73msgsg6lfsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTStvRjhLUkJlQjRwZ2FN
            VmFoR0dDdStCQ2ZXeUNabTk2UERwaWRPY0Z3CnpxYkxlQWFLUVlzUnYrakFwMFc3
            TjYrd28ycUpFK2FwTFRLVFk3RFNVaVkKLS0tIFBkdFJkOTlZanhwR24wb3JsTWpH
            dmQ3V1RMNGovK1dMcmtCakYxY3g3dm8KLSjfQ77FejV5aW1NjIaurXUQPvBXtzIv
            0GKtD4T/NUjHMOEp3lqFgnnT7bYv9VoJYJvw5Stqem8blu2q591BKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-15T06:53:46Z"
    mac: ENC[AES256_GCM,data:vta0ir8URr+DhWtr/UBFbNRSm2tC03MojFDzbQzLnuwUNv+Ap9Rp1tKPhhRgh5p1SS3VioUfpVBMS98QGlqsmDV/X11XHNxC7sR5IyaP1L/xzJRvnJx4WaxeWp6sMqGLFdSVj8PydPbE7ssIqAgabi7QqkOwvdi53Iyq+17x3ak=,iv:mxz8tOiR1pobIRF5imuCuVIAfSiSNPjSh9w4BF/VYOw=,tag:/Hr2AMMHeT2rhENhvQl8zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
