apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:7xZxWF0m0WuWmYitULj1rmP4wsFhFBYp,iv:npNqYMgymxVXeCKGbaRa0Y15dnlAIaOcEbSgbiNW8Q4=,tag:BZNUx28eJfOVeBh3CNwHnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s09z34n5t8v08wgwkfa2fd2w8lcaadd5gkpdw0dqyku2ln73msgsg6lfsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQmtjRk1rNm9xbzRMRFFH
            d20zc0F5ZXdtNWV6ZlVGOFVTNjFDa0U4RW1ZCi9OcjdwbGpGVEFiME4yWnpjQWh6
            dHBGMUUwcEdYdzFjRVFBdXRuWkxBcmcKLS0tIEN6c0ZSLzgvR2tnWnpCLzJhWVJC
            QjlSNFR6UWJQUGhWY0Q2ZEo1Zi9nRG8K0dG1MiFunAk5zbUrZ39Nr76L7A8sAIvs
            jMkc8/kz7n4hmHIc1zcXlHKaHIZIPU25KVluzH9y7RcHqWEZbKzLyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T01:29:08Z"
    mac: ENC[AES256_GCM,data:hJlGceutfZNK94GCj/sSjTfBUdBO71CHimcUmzzVmCiRh7B6necMNKKMbeiVIpPhfIyz0xU5yNIguavbtIcJUzbCUgYsPaiR71PYlmKDcZWCosF3JSLgdHK65qTPXOKmV3yD1qYOeGdMKaXMFMIYoSxJAESzn73A/VJ3evfsEVE=,iv:pJFleqgEpaagL0whZ55iuhlfa2W6ALkt1LdJDU9vVpY=,tag:pgZTYTA3bk+nFPelEkiVTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
