---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mastodon
  namespace: flux-system
spec:
  dependsOn:
    - name: democratic-csi-iscsi
      namespace: kube-system
    - name: postgres16-rw
      namespace: database
  targetNamespace: mastodon
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/mastodon/mastodon/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
