
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
#  - ./recyclarr/ks.yaml
#  - ./qbittorrent/ks.yaml
#  - ./sabnzbd/ks.yaml
#  - ./plex/ks.yaml
