---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrypted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      scrypted:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 65542 # gladius:external-services

        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/scrypted
              tag: 0.122.0@sha256:f69bbb25463d027d7f690ffbc672ba19ee6fbff5117b4450aebbd0a29a52a8e5
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 136m
                memory: 1024Mi
              limits:
                memory: 8192Mi

    service:
      app:
        controller: scrypted
        ports:
          http:
            port: 11080
            primary: true
          rebroadcast1:
            port: 34135
          rebroadcast2:
            port: 34136

    ingress:
      app:
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: freenas-iscsi-csi
        size: 1Gi
        advancedMounts:
          scrypted:
            app:
              - path: /server/volume
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      cache-npm:
        type: emptyDir
        globalMounts:
          - path: /.npm
      media:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: ${SECRET_NFS_MEDIA}
      recs:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: ${SECRET_NFS_CCTV}
        globalMounts:
          - path: /recs
