---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mtr-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mtr-exporter:
        containers:
          app:
            image:
              repository: ghcr.io/mgumz/mtr-exporter
              tag: 0.4.0
            command: ["mtr-exporter", "-jobs", "/jobs.txt"]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ALL] }
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 120M
        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: mtr-exporter
        ports:
          http:
            port: 8080
    serviceMonitor:
      app:
        serviceName: mtr-exporter
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 60s
            scrapeTimeout: 1m
    persistence:
      config-file:
        type: configMap
        name: mtr-jobs
        defaultMode: 0700
        advancedMounts:
          mtr-exporter:
            app:
              - path: /jobs.txt
                subPath: jobs.txt
