---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bino
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json
    defaultPodOptions:
      imagePullSecrets:
        - name: dockerconfigjson-github-com

    controllers:
      bino:
        annotations:
          reloader.stakater.com/auto: 'true'
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: bino-secret
          migrate:
            image:
              repository: ghcr.io/zeroecks/bino-next-migrate
              tag: &binoVersion 19
            envFrom: *envFrom
        containers:
          app:
            image:
              repository: ghcr.io/zeroecks/bino-next
              tag: *binoVersion
            envFrom: *envFrom
            env:
              AUTH_REDIRECT_PROXY_URL: https://{{ .Release.Name }}.${SECRET_DOMAIN}/api/auth
            resources:
              requests:
                cpu: 15m
                memory: 50M
            probes:
              liveness:
                enabled: true
                spec:
                  path: /api/healthz
                  initialDelaySeconds: 3
                  failureThreshold: 5
                  timeoutSeconds: 2
                  periodSeconds: 30

    service:
      app:
        controller: bino
        ports:
          http:
            port: &port 3000

    ingress:
      internal:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
