---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zipline
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false

    controllers:
      zipline:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: zipline-secret

        containers:
          app:
            image:
              repository: ghcr.io/diced/zipline
              tag: 3.7.13
            envFrom: &envFrom
              - secretRef:
                  name: zipline-secret
            env:
              # Core config
              CORE_RETURN_HTTPS: "true"
              CORE_COMPRESSION_ENABLED: "true"
              CORE_COMPRESSION_THRESHOLD: "200mb"
              CORE_COMPRESSION_ON_DASHBOARD: "true"
              # Datasources
              DATASOURCE_TYPE: "local"
              DATASOURCE_LOCAL_DIRECTORY: "/media"
              # Exif
              EXIF_REMOVE_GPS: "true"
              # Features
              FEATURES_INVITES: "false"
              FEATURES_ROBOTS_TXT: "false"
              FEATURES_USER_REGISTRATION: "false"
              # Uploader
              UPLOADER_DEFAULT_FORMAT: "DATE"
              UPLOADER_DISABLED_EXTENSIONS: ""
              UPLOADER_FORMAT_DATE: "YYYY-MM-DD_HH-mm-ss"
              UPLOADER_DEFAULT_EXPIRATION: "60d"
              # URLs
              URLS_ROUTE: /go
              URLS_LENGTH: 6
              # Website
              WEBSITE_TITLE: "MelSend"
              WEBSITE_SHOW_FILES_PER_USER: "false"
              WEBSITE_SHOW_VERSION: "false"
            resources:
              requests:
                cpu: 5m
                memory: 256Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: zipline
        ports:
          http:
            port: 3000

    ingress:
      external:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "z.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: freenas-iscsi-csi
        size: 64Gi
