apiVersion: v1
kind: Secret
metadata:
    name: zipline-secret
    namespace: kube-system
stringData:
    CORE_SECRET: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s09z34n5t8v08wgwkfa2fd2w8lcaadd5gkpdw0dqyku2ln73msgsg6lfsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTStvRjhLUkJlQjRwZ2FN
            VmFoR0dDdStCQ2ZXeUNabTk2UERwaWRPY0Z3CnpxYkxlQWFLUVlzUnYrakFwMFc3
            TjYrd28ycUpFK2FwTFRLVFk3RFNVaVkKLS0tIFBkdFJkOTlZanhwR24wb3JsTWpH
            dmQ3V1RMNGovK1dMcmtCakYxY3g3dm8KLSjfQ77FejV5aW1NjIaurXUQPvBXtzIv
            0GKtD4T/NUjHMOEp3lqFgnnT7bYv9VoJYJvw5Stqem8blu2q591BKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-15T10:14:35Z"
    mac: ENC[AES256_GCM,data:vFlBwN42qcM2p/l2ehcDSabJ0J0/7Bd5RCuW8nO3/LoVYTzyp/xDDuLkKuc3Y+BtlC539Z4BP8YjyQjrl9/VzT/pblKXfFwcgk9NpyKnIJLei+zoR7EDSfkIdLkYo10fBpZRISAmna2aiUdDiVBb6o68bENSiAq2pMBfSCXtWKA=,iv:NkMWbrc/7dZmAIdW6PWfZdcW5fz2hQNGShcOZCrYjYM=,tag:j/sgfipJCF2N88LOys6wFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
