---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: slskd
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/slskd/slskd
      tag: 0.21.3

    env:
      TZ: ${TIMEZONE}
      PUID: 1026
      PGID: 100
      SLSKD_HTTP_PORT: &port 80
      SLSKD_SLSK_LISTEN_PORT: &soulseekPort 50300
      SLSKD_REMOTE_CONFIGURATION: true
      SLSKD_DOWNLOADS_DIR: "/media/downloads/slsk/complete"
      SLSKD_INCOMPLETE_DIR: "/media/downloads/slsk/incomplete"
      SLSKD_SHARED_DIR: "/media/music"
      SLSKD_METRICS: true
      SLSKD_METRICS_NO_AUTH: true
      SLSKD_UPLOAD_SLOTS: 2
      SLSKD_UPLOAD_SPEED_LIMIT: 10000

    envFrom:
      - secretRef:
          name: slskd-secret

    service:
      main:
        ports:
          http:
            port: *port
      soulseek:
        enabled: true
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.1.13
        ports:
          incoming:
            enabled: true
            port: *soulseekPort
            protocol: TCP
            targetPort: *soulseekPort

    volumeClaimTemplates:
      - name: app
        mountPath: /app
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: freenas-iscsi-csi

    persistence:
      media:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: ${SECRET_NFS_MEDIA}
        mountPath: /media

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      runAsNonRoot: true
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]

    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    resources:
      requests:
        cpu: 400m
        memory: 128Mi
      limits:
        memory: 2Gi
