---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: mosquitto-acl-configmap
    files:
      - acl.conf=./resources/acl.conf
  - name: mosquitto-configmap
    files:
      - mosquitto.conf=./resources/mosquitto.conf
generatorOptions:
  disableNameSuffixHash: true
