---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app mastodon
  namespace: mastodon
spec:
  interval: 60m
  chart:
    spec:
      chart: *app
      version: 4.2.5
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 60m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      storageClass: "democratic-csi-iscsi"

    image:
      registry: ghcr.io
      repository: glitch-soc/mastodon
      tag: nightly.2024-02-13

    environment: production
    adminUser: "melody"
    adminEmail: "melody@${SECRET_DOMAIN}"

    existingSecret: "mastodon-secrets"

    enableSearches: true
    enableS3: false
    useSecureWebSocket: true
    local_https: true
    localDomain: "toot.${SECRET_DOMAIN}"
    webDomain: "toot.${SECRET_DOMAIN}"
    defaultLocale: en

    smtp:
      port: 8025
      from_address: "notifications@${SECRET_DOMAIN}"
      domain: "${SECRET_DOMAIN}"
      delivery_method: smtp
      openssl_verify_mode: none
      enable_starttls_auto: true
      tls: false
      auth_method: plain
      existingSecret: "mastodon-secrets"
      existingSecretLoginKey: "SMTP_LOGIN"
      existingSecretPasswordKey: "SMTP_PASSWORD"
      existingSecretServerKey: "SMTP_SERVER"

    web:
      replicaCount: 1
      containerPorts:
        http: 3000
      resources:
        requests:
          memory: 512Mi
        limits:
          memory: 2048Mi
      podAnnotations:
        reloader.stakater.com/auto: "true"

      service:
        type: ClusterIP
        ports:
          http: 80
        externalTrafficPolicy: Cluster

    sidekiq:
      replicaCount: 1
      resources:
        requests:
          memory: 512Mi
        limits:
          memory: 2048Mi
      podAnnotations:
        reloader.stakater.com/auto: "true"

    streaming:
      replicaCount: 1
      containerPorts:
        http: 8080
      resources:
        requests:
          memory: 512Mi
        limits:
          memory: 1024Mi

      podAnnotations:
        reloader.stakater.com/auto: "true"

      service:
        type: ClusterIP
        ports:
          http: 80

    tootctlMediaManagement:
      enabled: true
      removeAttachments: true
      removeAttachmentsDays: 7
      removeCustomEmoji: false
      removePreviewCards: true
      removePreviewCardsDays: 30
      removeAvatars: true
      removeAvatarsDays: 30
      removeHeaders: true
      removeHeadersDays: 30
      removeOrphans: true
      includeFollows: false
      cronSchedule: "14 3 * * *"
      failedJobsHistoryLimit: 3
      successfulJobsHistoryLimit: 1
      concurrencyPolicy: Allow

    initJob:
      precompileAssets: true
      migrateDB: true
      migrateElasticsearch: true
      createAdmin: true
      backoffLimit: 10

    persistence:
      enabled: true
      existingClaim: *app
      mountPath: /opt/bitnami/mastodon/public/system

    volumePermissions:
      enabled: false

    externalDatabase:
      host: "mastodon-rw.mastodon.svc.cluster.local"
      port: 5432
      user: app
      database: app
      existingSecret: "mastodon-app"
      existingSecretPasswordKey: "pgpass"

    externalRedis:
      host: "redis.database.svc.cluster.local"
      port: 6379
      password: ""

    elasticsearch:
      enabled: true
      sysctlImage:
        enabled: true
      security:
        enabled: false
        existingSecret: ""
        tls:
          restEncryption: false
      master:
        replicaCount: 1
      coordinating:
        replicaCount: 1
      data:
        replicaCount: 1
      ingest:
        replicaCount: 1
      service:
        ports:
          restAPI: 9200

    redis:
      enabled: false
    postgresql:
      enabled: false
    minio:
      enabled: false

    apache:
      enabled: false
