apiVersion: v1
kind: Secret
metadata:
    name: mastodon-secret
    namespace: mastodon
stringData:
    MASTODON_ADMIN_PASSWORD: ENC[AES256_GCM,data:FnxmQA==,iv:NS2AtQU0KA/QRfPMwP4fSTHTbp92WnFyi0H8nm0rLn0=,tag:ipZF6drHQat/atSVbc7ftQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:lW0UTSKoJpvojGNtlQwtz5SGksnGe8+J0B1YNMvHoALHwObQT1DIcpLp6NjEpbx2mNEEL5wBWEq8DkxuD7Z5Dt4tVrbIjuowENRoIbAR7jgWj04r74CUUBoy7mdKSgOu96QBeaKL3tsb/iA7nDbHLEJWBLFpWMtQRU5Ci827OJE=,iv:98wlMWOVmUQQTVvXM/pWjgLuXrY1jtGWHMyRMRbXGDg=,tag:2T8z6lhtqSkFLxxubgnwQA==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:jvM07LW7AAn8FBwVXNkMztdQHh6RzXxroyfOQyoMeitI7b4ceUNYWCODsxIOqXtlM9jJxAvnl+j7/wO55L9g59cl+JImEGIy4oN2MxB3ZDpn5S5QTmT0i55lUaisJ+EvZvppqbCwMCXT2GUCENsibWBbDeeNtUAkCSWs2+pkkb8=,iv:Y2QXbnJ4HHLdOjiT7ukfSfBYXaVRA1MU27npq5PDQGo=,tag:0TXbqX/PLQZ6qyOHy0HksA==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:cpjKnuArm8CxrPpLKnzLE4QJfr99a7q8LO7NNNhOSbg4twywlZXRSKFbIs8=,iv:O8MBB2eeXa6+iBGV0y+ZlY2mnyArQfo8AQ2zJA8suuw=,tag:lFcECYn4B6AqCR7yULCYXw==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:ohC9wI5EfIy1OczH4QmMiBdacUUAepvQbbQ+B+JYiJE4Z0+KYSlHqZloio5MPx57DIJ7cToPvhWAUiqrlBixK8DRahfQ+c3F+UfQfdCO1mWdX/jjLpXGZA==,iv:wCKpc2HvbNUdQIsxmgslzD8gA/s3R1a6bPis/e6Cjf4=,tag:ocSSlyHbDVlfPx5Q+f0efw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:0sIhLBvCHK/hgj4=,iv:KdzqUl1BFQ+RNmz9ba1uA/47a0IcfE7jG3/T8fW9gaQ=,tag:sE2e3Hvfb/Vop+x46veGpw==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:drwbB+c1dtUvVkujEqwnVmzIu+YsX6c8m2vwpHwCARoa7BWE4H3cWuHHJnZhvZ9Z98EfQppTpU/tnV0y+dgPisRTzwC4GnidhPJxW/ROXzwrMHE9wExNQ5SEHx2DVNbpdBg636iGcBEbqempeXBBgrxYelKk2qpV8t2aRIVphrU0kUCeNMuKMV9UDitlJY4d,iv:221uk/iwH1nPoUeAI8WPvcLa11TTYyTvKm2oSNaQKRg=,tag:dPCyOd6A6Rh68spZTT0hMA==,type:str]
    SMTP_SERVER: ENC[AES256_GCM,data:JI3gh0L58qcXCGzV6KwtovDAnWlm,iv:qpAQbAK3uhBtVWJCnh2Gmznt+cPepiAeFKWWPMNzgj4=,tag:u/CdfQ+ElGDfYaoGy7Eb+Q==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:ISFSGWFwyuMsFcSi+E5lW7yIxw==,iv:nCNnyqlvni+fEzDGKkIGyW2bX9nVdj6ZyXTQrTVy5oY=,tag:/UWBV+0ZO8elvExYSNIH+g==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:J9yBS5n5m7U=,iv:VFBJ7pT5zLDDSmhj03BHpphEj3I8/luiTTKlU4EIflY=,tag:mEAzWqv1pRFV3GsnQTwxyw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:pfcKijQsu81mUAZ4ms8qm703W8stVDX+VaKRpmvRaCMJHV6glMPMnQ==,iv:wkl9/GkDNdKH8Lgdtgh/gzKrUy//qmE3AGJx+SbkPNo=,tag:KGIWVXARgg4QFsJMwad7Yg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ziyC6GhTzg0=,iv:6i6Mm/0yDQZMh5JCDbtsrISHrYQz6d9OAEazSlDQSPY=,tag:bPN40+kz2fUHXR3c0FS/UQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:GLHbVb1CZPa+w9Srq5j0G5Hhvw==,iv:vUxu90EusOucEkwrqSTMLciLi8mykJqkHkgcd/q/T3c=,tag:hssLCrxUfhl7W3bmywfC5g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:FaIUlEvJdVjuy24JjW9VExORyL8hSLg=,iv:Z/0nu23yVGbm2M+zFjvWpb+x0hRXm22SXbEbpLWNsK4=,tag:Rr7BmdqLH7d5cpFZ4t3y8w==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:lwdrxNDR+ewWRA1RIjELr8FzJPQ=,iv:soZeZ3O/AKzJY1/M/BIQAXk5Kcaa9Oxmk3bOalFfe7k=,tag:2RRYZQafIdvw6xRM7PpKhw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sWyVdNP88UIPPgdzOs3s5wAo7cWELbUHgCfcnfW+FSyiQ44qh5cQgpnA1Q==,iv:1EQo5UMBWfN2I7EUbp1Y6DSKCv3f4cWF12XxsOv6c4E=,tag:CluO5UrVwHryEl/ZcSjsIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s09z34n5t8v08wgwkfa2fd2w8lcaadd5gkpdw0dqyku2ln73msgsg6lfsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTStvRjhLUkJlQjRwZ2FN
            VmFoR0dDdStCQ2ZXeUNabTk2UERwaWRPY0Z3CnpxYkxlQWFLUVlzUnYrakFwMFc3
            TjYrd28ycUpFK2FwTFRLVFk3RFNVaVkKLS0tIFBkdFJkOTlZanhwR24wb3JsTWpH
            dmQ3V1RMNGovK1dMcmtCakYxY3g3dm8KLSjfQ77FejV5aW1NjIaurXUQPvBXtzIv
            0GKtD4T/NUjHMOEp3lqFgnnT7bYv9VoJYJvw5Stqem8blu2q591BKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-17T01:46:48Z"
    mac: ENC[AES256_GCM,data:pdSG8ISYBNArF9zIwdKHcjCI3vxsJ0FF6PS94N3ZyNGEd/0+YBPXgZ+OGLYHUXG7DmmvNST7ra/VYGQYJ4/29+cuAcErTGEwfLjsYidkwZIWwfD+FWBEA0mEjJLGjjOVVCjHeEtQm1bze7pzWSw2uavUG9g1xPwfTw9MN7x9vQc=,iv:+vfuRHu98T0nTqC/T9aNa9uQFUvvL1Gdn+cFJoo1ugo=,tag:5YNifTOWirq81/ubKVz6Ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
