---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name digikam-mariadb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: digikam-mariadb
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Account
        mariadb-password: "{{ .password }}"
        mariadb-replication-password: "{{ .replication_password }}"
        mariadb-root-password: "{{ .root_password }}"
  dataFrom:
    - extract:
        key: "Digikam Mariadb"
      rewrite:
        - regexp:
            source: "(.*)"
            target: "epic_$1"
