---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name digikam-mariadb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: digikam-mariadb-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Account
        mariadb-password: "{{ .DIGIKAM_PASSWORD }}"
        mariadb-replication-password: "{{ .DIGIKAM_REPLICATION_PASSWORD }}"
        mariadb-root-password: "{{ .DIGIKAM_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: digikam-mariadb
