---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: digikam-mariadb
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 20.5.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      storageClass: freenas-iscsi-csi
    architecture: standalone
    auth:
      existingSecret: digikam-mariadb-secret
      database: main
    persistence:
      storageClass: freenas-iscsi-csi
      size: 32Gi
    primary:
      pdb:
        create: true
        minAvailable: 1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
