---
apiVersion: v1
kind: Service
metadata:
  name: postgres-bino-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bino-postgres.${SECRET_DOMAIN}
    io.cilium/lb-ipam-ips: 192.168.1.13
spec:
  type: LoadBalancer
  ports:
    - name: postgres-bino
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: cluster-bino
    role: primary
