apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:oX/f0OCnOm36iJkQZ3VG3ksrJuo41BeYQ4iSx/0SiupdXQ5jhmBVVg==,iv:cOcAp+aIf5a5oT9cjA59pwuYZcq7udZlIaoXIjX8Pys=,tag:FW5ZyC6Y1Itlc7Pz1g56FQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s09z34n5t8v08wgwkfa2fd2w8lcaadd5gkpdw0dqyku2ln73msgsg6lfsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYjZ5ekxwL1NidmNiUWtw
            c1pwODUzN0g0Mk1yak1YeTBKY3FSUTc3Q0ZNCmxTazNLMEpwc21oNGRhZWZDbDZm
            RkVMTjB5UURQc0JobkFsdVRtZTFtUEEKLS0tIGF0dVl0NGtoU1Vmb0NyVW5uMXdx
            WHR3S1ZFeWxqMlcxbzZ6b0ZjMUVDZTgKJAGeIa0euIMkS9+mpA9bREh9YAIqQ2gp
            XsQOLzOhZxfdTQnwWHvjxptk87eh0E9tOSbEGHTn0zCyNk+RScavyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T01:29:08Z"
    mac: ENC[AES256_GCM,data:j1rSioPHp+xKKiIRsEGcp8Iae+NG4IHpVLLoJbLQVeU0GTlQdZbePV3CWYOdgAI6Qgymxi+KRDmBCLqk4gYAd1KSdbEypm7mUCMEDga+4IyveLZmJv9mLGMxkoy8eJuQ2Yo6COwfD4aquH9qdh6i5JXZhmZSm4Xl0GNKB5JCRpU=,iv:M8A5LzZhXRtJuJS71bp5M7+4CU9eyUCMAi6Q0HAbJ4k=,tag:WYF8Qmit86l2SquSyDGluQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
