---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ocis-nfs
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ocis-nfs
spec:
  storageClassName: ocis-nfs
  capacity:
    storage: 1Mi # Size does not matter
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: ${SECRET_NFS_OCIS}
  mountOptions:
    - nfsvers=4.2
    - nconnect=4
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocis-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocis-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
